import akai from './akai.wav'
import clap from './clap.wav'
import control from './control.wav'
import dismal from './dismal.wav'
import drum from './drum.wav'
import guitar1 from './guitar1.wav'
import hihat from './hihat.wav'
import hiphop from './hiphop.wav'
import kick from './kick.wav'
import marchingband from './marchingband.wav'
import subbass from './subbass.wav'
import vocal1 from './vocal1.wav'
import chordA from './chordA.wav'
import chordG from './chordG.wav'
import chordF from './chordF.wav'
import chordEm from './chordEm.wav'
import chordC from './chordC.wav'
import cleanchordD01 from './cleanchordD01.wav'
import chordD from './chordD.wav'
import AHDNchord from './AHDNchord.wav'
import chordE from './chordE.wav'
import chordDeinzzwo from './chordDeinzzwo.wav'
import bassSlap from './bassSlap.wav'
import steelGuitar from './steelGuitar.wav'
import Electric from './Electric.wav'
import ChordsAmin from './ChordsAmin.wav'
export  {akai,clap,bassSlap,control,dismal,drum,guitar1,hihat,hiphop,kick,
    marchingband,subbass,vocal1,chordG,chordA,chordF,chordEm,chordE,chordC,
    cleanchordD01,chordD,AHDNchord,chordDeinzzwo,steelGuitar,Electric,ChordsAmin,};